// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package inventoryhistory

import metav1 "github.com/hinss/api/pkg/meta/v1"

const TableNameInventoryHistory = "inventoryhistory"

// InventoryHistory mapped from table <inventoryhistory>
type InventoryHistory struct {
	metav1.ObjectMeta
	OrderSn        string    `gorm:"column:order_sn;not null" json:"order_sn"`
	OrderInvDetail string    `gorm:"column:order_inv_detail;not null" json:"order_inv_detail"`
	Status         int32     `gorm:"column:status;not null" json:"status"`
}

// TableName InventoryHistory's table name
func (*InventoryHistory) TableName() string {
	return TableNameInventoryHistory
}
