// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/hinss/api/pkg/meta/v1"
)

const TableNameBanner = "banner"

// Banner mapped from table <banner>
type Banner struct {
	metav1.ObjectMeta
	Image      string    `gorm:"column:image;not null" json:"image"`
	// URL是一个跳转地址
	URL        string    `gorm:"column:url;not null" validate:"required" json:"url"`
	Index      int32     `gorm:"column:index;not null" validate:"required,lte=100" json:"index"`
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
