// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/hinss/api/pkg/meta/v1"
)

const TableNameBrands = "brands"

// Brands mapped from table <brands>
type Brands struct {
	metav1.ObjectMeta
	Name       string    `gorm:"column:name;not null" validate:"required" json:"name"`
	Logo       string    `gorm:"column:logo;default:'NULL'" json:"logo"`
}

// TableName Brands's table name
func (*Brands) TableName() string {
	return TableNameBrands
}
