// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/hinss/api/pkg/meta/v1"
)

const TableNameCategoryBrand = "category_brand"

// CategoryBrand mapped from table <category_brand>
type CategoryBrand struct {
	metav1.ObjectMeta
	CategoryID int32     `gorm:"column:category_id;not null" json:"category_id"`
	BrandID    int32     `gorm:"column:brand_id;not null" json:"brand_id"`
}

// TableName CategoryBrand's table name
func (*CategoryBrand) TableName() string {
	return TableNameCategoryBrand
}
