// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/hinss/api/pkg/meta/v1"
)

const TableNameGoodsCategoryBanner = "good_category_brand"

// GoodsCategoryBanner mapped from table <good_category_brand>
type GoodsCategoryBanner struct {
	metav1.ObjectMeta
	CategoryID int32     `gorm:"column:category_id;not null" json:"category_id"`
	BrandID    int32     `gorm:"column:brand_id;not null" json:"brand_id"`
}

// TableName GoodsCategoryBanner's table name
func (*GoodsCategoryBanner) TableName() string {
	return TableNameGoodsCategoryBanner
}
