// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/hinss/api/pkg/meta/v1"
)

const TableNameGoods = "goods"

// Goods mapped from table <goods>
type Goods struct {
	metav1.ObjectMeta
	CategoryID      int32     `gorm:"column:category_id;not null" json:"category_id"`
	BrandID         int32     `gorm:"column:brand_id;not null" json:"brand_id"`
	OnSale          bool      `gorm:"column:on_sale;not null" json:"on_sale"`
	GoodsSn         string    `gorm:"column:goods_sn;not null" json:"goods_sn"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	ClickNum        int32     `gorm:"column:click_num;not null" json:"click_num"`
	SoldNum         int32     `gorm:"column:sold_num;not null" json:"sold_num"`
	FavNum          int32     `gorm:"column:fav_num;not null" json:"fav_num"`
	Stocks          int32     `gorm:"column:stocks;not null" json:"stocks"`
	MarketPrice     float32   `gorm:"column:market_price;not null" json:"market_price"`
	ShopPrice       float32   `gorm:"column:shop_price;not null" json:"shop_price"`
	GoodsBrief      string    `gorm:"column:goods_brief;not null" json:"goods_brief"`
	ShipFree        bool      `gorm:"column:ship_free;not null" json:"ship_free"`
	Images          string    `gorm:"column:images;not null" json:"images"`
	DescImages      string    `gorm:"column:desc_images;not null" json:"desc_images"`
	GoodsFrontImage string    `gorm:"column:goods_front_image;not null" json:"goods_front_image"`
	IsNew           bool      `gorm:"column:is_new;not null" json:"is_new"`
	IsHot           bool      `gorm:"column:is_hot;not null" json:"is_hot"`
}

// TableName Goods's table name
func (*Goods) TableName() string {
	return TableNameGoods
}
