// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package inventory

import metav1 "github.com/hinss/api/pkg/meta/v1"

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	metav1.ObjectMeta
	Goods      int32     `gorm:"column:goods;not null" json:"goods"`
	Stocks     int32     `gorm:"column:stocks;not null" json:"stocks"`
	Version    int32     `gorm:"column:version;not null" json:"version"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
